### ISSUE TITLE
Make a Periodic Table ASAP

### ISSUE THREAD

**Issue by Hackerbone** [Hackerbone/CPProject#2]
**Please Note:- The  updated tasks are always  in italics & bold, so  keep up  to date  😄.
  Also you're not required to make a table.  Just make the arrays properly**
 <H1><i><b>ALWAYS COMPILE AND TEST YOUR CODE BEFORE  ISSUING A PULL REQUEST</i></b></H1>

<h1>Make a Periodic Table</h1>
<h2>Things to be there:</h2>
<ul>
<li>Atomic Number (Z)</li>
<li>Atomic Mass</li>
<li>Element Symbol</li>
<li>Element</li>
<li>Labled s-block, p-block, d-block, f-block(Different)</li>
<li>Element dictionary, about etc</li>
<li><i><b>Make a 2D array containing enough no. of empty elements so that when set up in a table, it looks as if  they're  in a periodic table.<br> For example : arrayname[160] = {"H", "  ", "  ",  "  ", "  ",  ..... total 16 spaces ,then..."He"  }</b></i></li>
</ul>
<hr>
<h3> Make Sure its well tabled with different blocks etc.</h3>
<h4> 
Compiling <br>
(LOOK IF YOU ARE  IN THE SAME DIRECTORY AS THE FILE, if not use cd Desktop/....)<br>
g++ filename.cpp<br>
a.exe<br>
<h5> Open a Pull Request after the completion</h5>
:)

**Comment by Hackerbone** [comment]
****Thanks Nigga for completing the work, merging and closing

**Comment by Virtulya** [comment]
Anytime.

On 11-Jan-2019 8:40 AM, "Sitaraman S" <notifications@github.com> wrote:

Closed #2 <https://github.com/Hackerbone/CPProject/issues/2>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Hackerbone/CPProject/issues/2#event-2067547561>, or mute
the thread
